# Generated by Django 5.1.2 on 2024-10-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description_listing_sold_listing_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='types',
            field=models.CharField(choices=[('REC', 'Disques'), ('CLO', 'Vêtements'), ('POS', 'Affiches'), ('MIS', 'Divers')], max_length=30),
        ),
    ]
